- name: restart td-agent.service
  systemd: 
    state: restarted
    name: td-agent

- name: network kernel parameters apply
  shell:
    cmd: sysctl -p

- name: ntp changes apply
  systemd: 
    state: restarted
    name: ntp